name: elements 
version: 0.1.2.1
summary: The Modern Periodic Table.
description: The modern periodic table using dart and flutter.
base: core18 
confinement: strict
apps:
    elements:
      command: Elements
      extensions: [flutter-master]
parts:
  elements:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
